--liquibase formatted sql
--changeset lnowogorski:6
create table if not exists category(
    id bigint primary key not null generated by default as identity,
    name varchar(255) not null,
    description text,
    slug varchar(255) not null
);