--liquibase formatted sql
--changeset lnowogorski:17
create table if not exists "order"(
    id bigint not null primary key generated by default as identity,
    placeDate timestamp not null,
    orderStatus varchar(32) not null,
    grossAmount decimal(6,2) not null,
    customer_id bigint not null,
    constraint fk_order_customer_id foreign key (customer_id) references customer(id)
);

create table if not exists order_row(
    id bigint primary key not null generated by default as identity,
    order_id bigint not null,
    product_id bigint not null,
    quantity int not null,
    price decimal(6,2) not null,
    constraint fk_order_row_order_id foreign key (order_id) references "order"(id),
    constraint fk_order_row_product_id foreign key(product_id) references product(id)
);