--liquibase formatted sql
--changeset lnowogorski:18
create table if not exists shipment(
    id bigint primary key not null generated by default as identity,
    name varchar(255) not null,
    price decimal(6,2) not null,
    type varchar(32) not null,
    default_shipment boolean default false
);