--liquibase formatted sql
--changeset lnowogorski:20
--alter table order_row alter column product_id type bigint;
--alter table order_row add shipment_id bigint;
--alter table order_row add constraint fk_order_row_shipment_id foreign key (shipment_id) references shipment(id);