create table if not exists payment(
                                      id bigint primary key generated by default as identity,
                                      name varchar(64) not null,
    type varchar(64) not null,
    check_payment boolean default false,
    note text
    );